config.go, graph.go
Reference breaking change in go/loader API
golang/tools@69db398fe0e69396984e3967724820c1f631e971
Fixes sourcegraph/srclib-go#30
=> Change SourceImports to ImportFromBinary to follow go/loader updates.

config.go, graph.go, scan.go
This is correct and more cross platform.
=> Use filepath.SplitList to split GOPATH.

.gitignore, .gitmodules, .travis.yml, README.md, config.go, testdata/expected/program/cgo_sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample/GoPackage.depresolve.json, testdata/expected/program/cgo_sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample/GoPackage.graph.json, testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods/GoPackage.graph.json, testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import/GoPackage.graph.json, testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains/GoPackage.graph.json, testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope/GoPackage.depresolve.json, testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope/GoPackage.graph.json, testdata/expected/program/go-sample-0/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg/GoPackage.graph.json, testdata/expected/program/go13-sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample/GoPackage.depresolve.json, testdata/expected/program/gopathtest/github.com/alice/mypkg/GoPackage.graph.json, testdata/expected/program/gopathtest/github.com/alice/mypkg2/GoPackage.graph.json, testdata/expected/program/gopathtest/sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest/GoPackage.graph.json, testdata/expected/program/minimal-go-stdlib/cmd/go/GoPackage.graph.json, testdata/expected/program/minimal-go-stdlib/dummy0/GoPackage.graph.json, testdata/expected/program/minimal-go-stdlib/fmt/GoPackage.graph.json
Fix Travis build.
The last time it was modified, 1.3 was stable and 1.4 was tip, which was needed for some changes. Now 1.4 is stable, so we can use that for main testing instead.
- Many test cases expected output needed to be updated.
- A bug with `GOROOTForCmd` incorrectly ignoring env vars needed to be fixed, see commit message of 686e98eec59e0bb0248fab82d745b871caaa62f0.
- Go 1.3 test was removed.
Resolves #37.
=> Travis: Use Go 1.4 since it's now stable, make tip allowed failure.

Makefile
Install godep into a local .bin folder. That way, it will always be accessible even if the user does not have $GOPATH/bin added to their $PATH.
This is an implementation of the alternative idea described in https://github.com/sourcegraph/srclib-go/pull/46#issuecomment-130409912. Review and thoughts are welcome.
Closes #46.
=> Rely on a locally installed copy of godep binary.

Makefile, graph.go, scan.go
- building .exe file on Windows/Cygwin
- rebuilding executable only if go files (except in Godeps) were changed
- enforcing slashes in unit and graph files to make the output of scan and graph commands consistent
=> Windows support

scan.go
This will fix build errors in repositories where some directories might contain source files from different packages, by ignoring those directories. Usually such directories are example code files, eg https://github.com/golang/go/tree/master/doc/progs, so it is okay to ignore them in the build.
=> scan: ignore dirs with multiple packages

scan.go
@shurcooL This fixes the issue with scanForPackages failing completely when a particular directory contains invalid source files. Now, source files in such directories will be ignored (although the subdirectories will be scanned).
=> Ignore dirs with invalid source files

config.go, scan.go
Up until now the assumption `sourcegraph repo path == git remote URI == go import path` was usually true. If we want to break this assumption, then we'll need some mapping between repo path and go import path. This mapping then needs to be used for creating the synthesized gopath (implemented in this PR) and for mapping other repositories' import paths back to the repo path (not yet implemented).
=> added ImportPathRoot config

graph.go
Currently the grapher only fetches deps (with go get) if IN_DOCKER_CONTAINER is true:
https://github.com/sourcegraph/srclib-go/blob/fd67bff078ee774c13278bd6e709ee4ef7c30136/graph.go#L150
This makes sense if you are running srclib in your development GOPATH; you don't want it checking out different revisions of your GOPATH code. But if you are running srclib-go on a dedicated server without Docker, you do want it to create a temporary GOPATH and fetch deps, just like it would if Docker were enabled.
The current behavior results in unresolved refs for any deps that aren't already in the GOPATH, which means a lot of unresolved refs if running on a dedicated, non-Docker server.
=> Fetch deps if SRCLIB_FETCH_DEPS env var is set

golang_def/def.go
=> golang_def: return proper keyword for const and interface

Makefile
- producing PWD env variable in Windows environment (points to current directory, uses Unix-style separators) to make godep work from $(PWD)/.bin
=> Windows + Cygwin/MSYS/MINGW support

depresolve.go, testdata/expected/src/github.com/sgtest/go15vendor/github.com/sgtest/go15vendor/GoPackage.graph.json, testdata/expected/src/github.com/sgtest/go15vendor/github.com/sourcegraph/john-test/hi/GoPackage.graph.json
This will fix references to Go-1.6-vendored code.
=> fix depresolve for Go 1.6 vendor dependencies

graph.go
This change will allow srclib-go to graph multiple packages together.
The benefit of this is that we can graph all source units of a repo
together, taking advantage of the caching in go/loader and gog packages,
to avoid doing duplicate work of loading and parsing the same dependencies
multiple times.
TODO: fix the global config setting in graph.go
=> graph: accept a list of source units as input to graph

gog/doc.go
Fixes an undesired fatal error when a Go file contains a comment such as the following referring to a file that does not exist.
```
//line doesntexist.go:4
package foo
/* ... */
```
=> gog: do not fail if the doc file cannot be opened

gog/doc.go, gog/graph.go, graph.go, vendor/vendor.json
This modifies the graphing code to log and ignore errors that occur
while graphing a single source unit, so that the graph data from
other source units is returned successfully.
=> graph: gracefully handle error in graphing single source unit

Makefile, scan.go
- `make srctest` work on Windows now, had to change path-like items to Unix-style in the unit's data to produce identical results on Windows and Unix systems' and adjust Makefile to set Windows-style `GOPATH` when running tests
=> Fixed `make srctest` on Windows

depresolve.go, testdata/expected/src/github.com/sgtest/go-misc/github.com/sgtest/go-misc/go_subrepo_import/GoPackage.depresolve.json, testdata/expected/src/github.com/sgtest/go-misc/github.com/sgtest/go-misc/go_subrepo_import/GoPackage.graph.json
This changes the ResolveDep method to use the vcs.RepoRootForImportPath
method to resolve external package import paths, which is more stable
than the earlier gosrc.Get call. Additionally, this new call does not
incur a GitHub API request.
This change also makes it so that the Unit name of the resolved dep is
modified to have the base set to the root of the clone URL of the repo.
This ensures that the ref is resolved to the proper def, since the
def will not have a custom import path in its unit name when graphed by
srclib-go (since srclib-go does not have information about a repo's
custom import paths).
For eg, the `golang.org/x/net/context.Context` def will have the def key:
Repo: github.com/golang/net
Unit: github.com/golang/net/context
UnitType: GoPackage
Path: Context
Note how the …
=> depresolve: use newer tools/go/vcs package to resolve import paths

depresolve.go, depresolve/depresolve.go
This makes `ResolveImportPath` callable from external packages. One instance where this will be called is in `sourcegraph.com/sourcegraph/sourcegraph/util/resolveutil` to resolve custom Go package import paths (upcoming PR).
=> Factor out depresolve logic into separate pkg

depresolve/depresolve.go
grpc imports paths do not follow the same pattern as the general `google.golang.org/...` case.
This is a quick and easy solution, to add a special case for grpc. A future investigation can see if it's viable to remove the special case optimization, or if it's still worth having it for performance reasons.
Fixes #88.
/cc @beyang
=> depresolve: Fix incorrect mapping for grpc import paths.

depresolve/depresolve.go
Some repos have their clone url set to GitHub, so the resolution is currently wrong.
Resolves https://app.asana.com/0/91952577398025/119909364822594
=> remove special casing of clone url resolution for sourcegraph repos

depresolve/depresolve.go, depresolve/depresolve_test.go, testdata/expected/src/github.com/sgtest/go15vendor/github.com/sgtest/go15vendor/GoPackage.depresolve.json
Fixed so that not all "google.golang.org" repos are treated the same, instead three (of the four) have special cases. These are for efficiency reasons, and because sourcegraph.com hosts their github.com mirrors.
Fixed bugs. Instead of doing a `strings.Replace` to get the `ToRepoCloneURL`, the cloneURLs are just put in for special cases, for example "google.golang.org/grpc".
Tests are added to ensure correctness and prevent regressions. The tests are marked with a build tag so that they are not called every time this repo is built, as depresolve makes network calls that can be slow.
These changes make depresolve more accurate, which in turn helps any project that wants a more accurate CloneURL resolution.
=> Depresolve: fixed bugs and special cases. 

gog/graph.go, gog/scope.go, testdata/expected/src/github.com/sgtest/go-misc/github.com/sgtest/go-misc/multiple_mains/GoPackage.graph.json
This is to avoid a path collision between an interface method's name and a parameter with the same name of another method of the same interface. Tried long to find some less radical workaround, found none. Proper fix needs major rewrite of this code based on AST traversal. Feeling bad...
=> crude workaround for path collisions
